source("https://rubygems.org")

gem('pg')
gem('rspec')
gem('sinatra')
gem('sinatra-contrib', :require => "sinatra/reloader")
gem("sinatra-activerecord")
gem("rake")
gem("capybara")
gem('launchy')
gem("pry")
